### ISSUE TITLE
News widget is missing support for show_image attr for card layout

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-News-Plugin#58]
**Describe the bug**

See title.  Since adding the `show_image` attr for the card layout in v2.3.0, the news widget is no longer displaying post thumbnails by default, as it's not accounted for/passed along to `UCF_News_Common::display_news_items()`.

There are also several other notices being thrown when other array indexes aren't set on `$instance` in `UCF_News_Widget->widget()` that should ideally be addressed with a fix for this.

See: https://github.com/UCF/UCF-News-Plugin/blob/master/includes/ucf-news-widget.php#L19-L55

**Steps to Reproduce**

1. Add a news widget in any widget location and assign it the card layout
2. Watch undefined index notices show up in logs
3. Verify that thumbnails in the card layout are not displayed by default

**Expected Behavior**

- Thumbnails in news widgets using the card layout should be shown by default
- Notices related to unset widget settings should not be thrown

**Possible Fix**

- Add field for `show_image` attr to the news widget form
- Add array index checks on `$instance` where necessary in `UCF_News_Widget->widget()`

**Your environment:**

n/a

**Additional context**

Reported by Mark Bennett in Teams

**Comment by jmbarne3** [comment]
All fixed in v2.3.2.
